### ISSUE TITLE
Squares instead of text on the theme previewer

### ISSUE THREAD

**Issue by m911t** [flathub/org.gnome.TextEditor#4]
![image](https://user-images.githubusercontent.com/78878262/178177494-3ee1e826-f753-4b5c-aa15-3849d9c5d7f1.png)
Enabling "use a custom font" fixes it.

**Comment by chergert** [comment]
This was most likely a system configuration issue, as the default font was not mapped into the application. I think the SDK/Platform provides it now, but not certain on that. Either way, we expect access to default fonts from GNOME within the editor.
